namespace BO
{
    public enum Area { GENERAL = 1, NORTH, SOUTH, CENTER, JERUSALEM };
    public enum Status { READY_TO_DRIVE, MIDDLE_DRIVING, IN_REFUELING, IN_TREATMENT, NEED_REFUELING, NEED_TREATMENT };
}
